#!/bin/sh

COLORF="$(echo $(xrdb -query | grep '*.color6'| awk '{print $NF}'))"
COLORN="$(echo $(xrdb -query | grep '*.color0'| awk '{print $NF}'))"

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width			2
bspc config single_monocle			true
bspc config borderless_monocle		true
bspc config focused_border_color    "$COLORF"
bspc config normal_border_color     "$COLORN"
bspc config window_gap              10
bspc config honor_size_hints		false

bspc rule --add Surf:surf           state=tiled
bspc rule --add Zathura:zathura     state=tiled
bspc rule --add MPlayer:xv		    state=floating desktop="^5"

polybar top &
polybar bottom &

